### ISSUE TITLE
Typo: 'emphatises' should be 'emphasizes'

### ISSUE THREAD

**Issue by agentwaj** [carlosbaraza/web-assembly-logo-presentation#1]
I assume 'emphasizes' is the word you meant to use for the second point in the logo inspiration. I cannot submit a PR because I don't have InDesign.

**Comment by carlosbaraza** [comment]
Epic false friend from my native language (Spanish), where it is written `enfatizar`. I guess I will keep it like this in honor of my native language and my laziness, given that it's a long time since the contest is over.
